---
name: test-main

on:
  push:
    branches: [main]

permissions: {}

jobs:
  test-main:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
        with:
          go-version: "1.19.5"
          cache: true
      - uses: aquaproj/aqua-installer@61e2563dfe7674cbf74fe6ec212e444198a3bb00 # v2.0.2
        with:
          aqua_version: v2.2.1
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}
      - run: golangci-lint run
      - run: go test -v ./... -race -covermode=atomic
