---
name: test
on: pull_request
jobs:
  test:
    uses: suzuki-shunsuke/go-test-full-workflow/.github/workflows/test.yaml@98b1d118f22667c10788ac678906b0caef8909ba # v2.0.0
    with:
      aqua_version: v2.44.0
    permissions:
      pull-requests: write
      contents: read

  integration-test:
    runs-on: ubuntu-latest
    permissions: {}
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version-file: go.mod
      - run: go run ./cmd/ci-info run
        env:
          GITHUB_TOKEN: ${{github.token}}
